workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      node: 20
      groups:
        - google_play
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build web assets
        script: |
          cd frontend
          mkdir -p www
          cp *.html www/ 2>/dev/null || true
          cp *.css www/ 2>/dev/null || true
          cp *.js www/ 2>/dev/null || true
          cp manifest.json www/ 2>/dev/null || true
          cp -r icons www/ 2>/dev/null || true
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync android
      - name: Build Android APK
        script: |
          cd frontend/android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk

